#!/usr/bin/env sh

# Start the README with a warning message that it's machine generated
cat > README.md <<- END
<!-- This file is automatically generated! -->
<!-- Do not manually edit! To make changes, see build_readme.sh instead. -->

END

# Add a dynamic button to run this project on binder
cat >> README.md <<- END
Click this button [![Binder](https://mybinder.org/badge_logo.svg)](`git config --get remote.origin.url`/HEAD)
 to run this project!

END